name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.13.0, 12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup GIT user
      uses: fregante/setup-git-user@v1

    - name: Run tests with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn test-ci
    - run: yarn build
